#!/usr/bin/env bash
# Publish Godogen runtime files into a target game repo.
#
# Usage:
#   ./publish.sh --engine godot|bevy|babylon --agent claude|codex --out <dir> [--force]
#   ./publish.sh --engine godot|bevy|babylon --agent claude|codex <dir> [--force]
#
# A published repo carries only docs: the runtime manifest (CLAUDE.md / AGENTS.md),
# a per-engine guide (<engine>.md), and the asset-gen skill. The agent scaffolds
# the game itself from the engine guide — no project scaffold is shipped.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
HELPERS="$REPO_ROOT/scripts"

ENGINE=""
AGENT=""
OUT=""
FORCE=0

usage() {
    sed -n '1,10p' "$0" >&2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --engine) ENGINE="${2:-}"; shift 2 ;;
        --agent)  AGENT="${2:-}";  shift 2 ;;
        --out)    OUT="${2:-}";    shift 2 ;;
        --force)  FORCE=1;         shift   ;;
        -h|--help) usage; exit 0 ;;
        -*) echo "error: unknown option $1" >&2; usage; exit 1 ;;
        *)
            if [ -n "$OUT" ]; then
                echo "error: target specified more than once" >&2
                exit 1
            fi
            OUT="$1"
            shift
            ;;
    esac
done

case "$ENGINE" in
    godot)   ENGINE_DISPLAY="Godot" ;;
    bevy)    ENGINE_DISPLAY="Bevy" ;;
    babylon) ENGINE_DISPLAY="Babylon.js" ;;
    *) echo "error: --engine must be godot, bevy, or babylon" >&2; usage; exit 1 ;;
esac

# Root for runtime-loaded generated assets, substituted into the asset docs.
case "$ENGINE" in
    babylon) RUNTIME_ASSET_DIR="src/assets" ;;
    *)       RUNTIME_ASSET_DIR="assets" ;;
esac

case "$AGENT" in
    claude)
        MANIFEST="CLAUDE.md"
        SKILLS_DIR_REL=".claude/skills"
        AGENT_NAME="Claude"
        ASSET_SKILL_COMMAND="/asset-gen"
        ;;
    codex)
        MANIFEST="AGENTS.md"
        SKILLS_DIR_REL=".agents/skills"
        AGENT_NAME="Codex"
        ASSET_SKILL_COMMAND="\$asset-gen"
        ;;
    *) echo "error: --agent must be claude or codex" >&2; usage; exit 1 ;;
esac

ASSET_GEN_SKILL_DIR="$SKILLS_DIR_REL/asset-gen"
ENGINE_GUIDE_FILE="$ENGINE.md"

if [ -z "$OUT" ]; then
    echo "error: --out <target_dir> is required" >&2
    usage
    exit 1
fi

TARGET="$(cd "$OUT" 2>/dev/null && pwd || (mkdir -p "$OUT" && cd "$OUT" && pwd))"

if [ "$FORCE" -eq 1 ] && [ -d "$TARGET" ]; then
    echo "Force: cleaning $TARGET"
    rm -rf "${TARGET:?}"
    mkdir -p "$TARGET"
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Publishing $ENGINE/$AGENT to: $TARGET"

# --- Skills: asset-gen, our other skills, and the vendors' skills for the CLIs asset-gen drives ---
mkdir -p "$TMP/skills/asset-gen"
rsync -a --delete --exclude='__pycache__/' "$REPO_ROOT/asset-gen/" "$TMP/skills/asset-gen/"
for d in "$REPO_ROOT"/skills/*/ "$REPO_ROOT"/vendor/skills/*/; do
    [ -f "$d/SKILL.md" ] && rsync -a "$d" "$TMP/skills/$(basename "$d")/"
done
cp "$REPO_ROOT"/vendor/skills/LICENSE-* "$REPO_ROOT"/vendor/skills/VERSIONS "$TMP/skills/" 2>/dev/null || true

python3 "$HELPERS/render_dir.py" "$TMP/skills" \
    "AGENT_NAME=$AGENT_NAME" \
    "ASSET_GEN_SKILL_DIR=$ASSET_GEN_SKILL_DIR" \
    "ASSET_SKILL_COMMAND=$ASSET_SKILL_COMMAND" \
    "RUNTIME_ASSET_DIR=$RUNTIME_ASSET_DIR"

if [ "$AGENT" = "codex" ]; then
    python3 "$HELPERS/generate_codex_metadata.py" "$TMP/skills"
fi

mkdir -p "$TARGET/$SKILLS_DIR_REL"
rsync -a --delete "$TMP/skills/" "$TARGET/$SKILLS_DIR_REL/"
echo "Installed skills: $(ls "$TMP/skills" | grep -v '^[A-Z]' | tr '\n' ' ')"

# --- Manifest: the runtime process doc ---
MANIFEST_TMP="$TMP/manifest"
mkdir -p "$MANIFEST_TMP"
cp "$REPO_ROOT/prompts/runtime.md" "$MANIFEST_TMP/$MANIFEST"
python3 "$HELPERS/render_dir.py" "$MANIFEST_TMP" \
    "ENGINE_NAME=$ENGINE_DISPLAY" \
    "ENGINE_GUIDE_FILE=$ENGINE_GUIDE_FILE" \
    "ASSET_SKILL_COMMAND=$ASSET_SKILL_COMMAND"
cp "$MANIFEST_TMP/$MANIFEST" "$TARGET/$MANIFEST"
echo "Created $MANIFEST"

# --- Per-engine guide (literal markdown) ---
cp "$REPO_ROOT/engines/$ENGINE.md" "$TARGET/$ENGINE_GUIDE_FILE"
echo "Created $ENGINE_GUIDE_FILE"

# --- Per-engine tools (capture, animation lab, ...), when the engine has them ---
if [ -d "$REPO_ROOT/engines/${ENGINE}_tools" ]; then
    mkdir -p "$TARGET/tools"
    cp "$REPO_ROOT/engines/${ENGINE}_tools/"* "$TARGET/tools/"
    chmod +x "$TARGET"/tools/*.py 2>/dev/null || true
    echo "Created tools/: $(ls "$REPO_ROOT/engines/${ENGINE}_tools" | tr '\n' ' ')"
fi

# --- Git LFS for generated binaries: paid assets are committed, not regenerated ---
if [ ! -f "$TARGET/.gitattributes" ]; then
    for ext in glb gltf bin fbx png jpg jpeg webp gif ogv mp4 webm mov wav ogg mp3 flac; do
        printf '*.%s filter=lfs diff=lfs merge=lfs -text\n' "$ext"
    done > "$TARGET/.gitattributes"
    echo "Created .gitattributes (Git LFS)"
fi

# --- .gitignore (published instruction files are regenerated by publish.sh) ---
if [ ! -f "$TARGET/.gitignore" ]; then
    {
        if [ "$AGENT" = "claude" ]; then
            printf '.claude\nCLAUDE.md\n'
        else
            printf '.agents\nAGENTS.md\n.codex\n'
        fi
        printf '%s\n' "$ENGINE_GUIDE_FILE"
        printf '/tripo-out\n'
        case "$ENGINE" in
            godot)
                printf 'screenshots\n.godot\n*.import\nbin/\nobj/\n'
                # textures the importer unpacks from each GLB (car.glb -> car_Color_<id>.jpg), rebuilt on import
                printf 'assets/**/*_Color_*\nassets/**/*_NormalGL_*\nassets/**/*_ORM_*\n'
                ;;
            bevy)
                printf '/target\n/screenshots\n'
                ;;
            babylon)
                printf '/node_modules\n/dist\n/screenshots\n'
                ;;
        esac
    } > "$TARGET/.gitignore"
    echo "Created .gitignore"
fi

git -C "$TARGET" init -q 2>/dev/null || true
git -C "$TARGET" lfs install --local >/dev/null 2>&1 || echo "note: git-lfs not installed — assets would be committed as plain blobs (setup.md)"

echo "Done."
